version: '3'

tasks:
  lint:
    summary: |
      Lint source code with black and isort.
    cmds:
      - black .
      - isort .
      - autoflake .
  clean:
    summary: Remove temporary and cache files.
    cmds:
      - find . -name '*.pyc' | xargs rm -rf
      - find . -name '*__pycache__' | xargs rm -rf
      - find . -name '*.cache' | xargs rm -rf
