version: '3'

tasks:
  lint:
    desc: |
      Lint source code with various utilities.
    cmds:
      - black .
      - isort .
      - autoflake .
  clean:
    desc: Remove temporary and cache files.
    cmds:
      - find . -name '*.pyc' | xargs rm -rf
      - find . -name '*__pycache__' | xargs rm -rf
      - find . -name '*.cache' | xargs rm -rf
